kind: pipeline
type: docker
name: deploy-frontend

trigger:
  event:
    - custom

steps:
  - name: install-and-build
    image: node:18-alpine
    commands:
      - npm install
      - npm run build

  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t lms-frontend .

  - name: deploy-over-ssh
    image: alpine:latest
    environment:
      SSH_HOST:
        from_secret: ssh_host
      SSH_USER:
        from_secret: ssh_username
      SSH_PASS:
        from_secret: ssh_password
    commands:
      - apk add --no-cache openssh sshpass
      - |
        sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no -p 22 $SSH_USER@$SSH_HOST "
          cd /mnt/data/deployments/lms-frontend
          git pull origin master
          npm install
          npm run build
          docker compose down
          docker compose build --no-cache
          docker compose up -d
          docker system prune -f
        "

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
