version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: lms-frontend
    container_name: lms-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
