export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';

// config
export const SET_THEME = 'SET_THEME';
export const SET_LANGUAGE = 'SET_LANGUAGE';

// profile
export const SET_PROFILE = 'SET_PROFILE';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const UPDATE_THEME = 'UPDATE_THEME';
export const UPDATE_NOTIFICATION_PREFERENCE = 'UPDATE_NOTIFICATION_PREFERENCE';
export const SET_LICENSE_EXPIRATION = 'SET_LICENSE_EXPIRATION';
export const SET_LINKED_DEVICES = 'SET_LINKED_DEVICES';
export const SET_PROFILE_STATUS = 'SET_PROFILE_STATUS';
export const SET_PROFILE_ERROR = 'SET_PROFILE_ERROR';
export const SET_PROFILE_LOADED = 'SET_PROFILE_LOADED';

// charts
export const SET_NODE_STATUS = 'SET_NODE_STATUS';
export const SET_NETWORK_STATUS = 'SET_NETWORK_STATUS';

// metrics page
export const SET_LIVE_METRICS = 'SET_LIVE_METRICS';
export const SET_HISTORICAL_METRICS = 'SET_HISTORICAL_METRICS';
export const APPEND_LIVE_METRIC = 'APPEND_LIVE_METRIC';
export const CLEAR_METRICS = 'CLEAR_METRICS';