export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_THEME = 'SET_THEME';

// profile
export const SET_PROFILE = 'SET_PROFILE';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const UPDATE_THEME = 'UPDATE_THEME';
export const UPDATE_NOTIFICATION_PREFERENCE = 'UPDATE_NOTIFICATION_PREFERENCE';
export const SET_LICENSE_EXPIRATION = 'SET_LICENSE_EXPIRATION';
export const SET_LINKED_DEVICES = 'SET_LINKED_DEVICES';
export const SET_PROFILE_STATUS = 'SET_PROFILE_STATUS';
export const SET_PROFILE_ERROR = 'SET_PROFILE_ERROR';